package ru.swayfarer.swl2.jfx.scene.controls.ui;


import javafx.scene.layout.*;
import javafx.geometry.*;
import javafx.scene.control.*;
import javafx.scene.text.*;
import javafx.scene.shape.*;
import javafx.scene.image.*;
import javafx.beans.value.*; 
import javafx.beans.property.*; 

import static javafx.scene.layout.Priority.*;
import ru.swayfarer.swl2.jfx.scene.controls.JfxButton;
import javafx.scene.layout.HBox;
import ru.swayfarer.swl2.jfx.scene.controls.JfxLabel;
import javafx.geometry.Insets;
import javafx.scene.layout.AnchorPane;
import ru.swayfarer.swl2.jfx.scene.controls.JfxTextField;
import javafx.scene.layout.VBox;


/** 
 * This class is autogenerated from fxml file
 */


public class UiFileBrowser {

	/** 
	 * The root node of ui
	 */

	public AnchorPane _root;

	public JfxLabel lblComment;;
	public JfxTextField txtFilePath;;
	public JfxButton btnBrowseFile;;

	/** 
	 * The default constructor.
	 */

	public UiFileBrowser() {

		initUi();
	}

	/** 
	 * The ui initialization and adding it to controller.
	 */

	public void initUi() {
		AnchorPane ctrl_1 = new AnchorPane();
		ctrl_1.setMinHeight(Double.NEGATIVE_INFINITY);
		ctrl_1.setPrefHeight(54.0);
		ctrl_1.setPrefWidth(600.0);
		ctrl_1.setMinWidth(Double.NEGATIVE_INFINITY);
		ctrl_1.setMaxWidth(Double.NEGATIVE_INFINITY);
		VBox ctrl_2 = new VBox();
		ctrl_2.setPrefHeight(54.0);
		AnchorPane.setTopAnchor(ctrl_2, 0.0);
		ctrl_2.setPrefWidth(600.0);
		AnchorPane.setRightAnchor(ctrl_2, 0.0);
		AnchorPane.setLeftAnchor(ctrl_2, 0.0);
		ctrl_2.setLayoutX(40.0);
		ctrl_2.setLayoutY(14.0);
		AnchorPane.setBottomAnchor(ctrl_2, 0.0);
		JfxLabel lblComment = new JfxLabel();
		this.lblComment = lblComment;
		lblComment.setText("Select a file...");
		VBox.setMargin(lblComment, new Insets(5.0, 0, 0, 14.0));
		HBox ctrl_3 = new HBox();
		JfxTextField txtFilePath = new JfxTextField();
		this.txtFilePath = txtFilePath;
		HBox.setHgrow(txtFilePath, ALWAYS);
		txtFilePath.setMaxWidth(1.7976931348623157E308);
		JfxButton btnBrowseFile = new JfxButton();
		this.btnBrowseFile = btnBrowseFile;
		btnBrowseFile.setText("...");
		HBox.setMargin(btnBrowseFile, new Insets(0, 0, 0, 5.0));
		ctrl_3.getChildren().addAll(txtFilePath, btnBrowseFile);
		VBox.setMargin(ctrl_3, new Insets(5.0, 0, 0, 0));
		ctrl_2.getChildren().addAll(lblComment, ctrl_3);
		ctrl_1.getChildren().addAll(ctrl_2);
		_root = ctrl_1;;
	}

	/** 
	 * The fit to parent method for two panes.
	 */

	private static void fitTo(Region paneFromFit, Region paneToFit) {
		paneToFit.prefWidthProperty().bind(paneFromFit.widthProperty());
		paneToFit.prefHeightProperty().bind(paneFromFit.heightProperty());
	}

	/** 
	 * Set this ui to some pane.
	 */

	public void initParent(Pane parent) {
		parent.getChildren().setAll(_root);
		fitTo(parent, _root);
	}
}
